const products=[
{name:'Main Character',file:'main-character',photo:'render-6.jpeg',color:'#df6b22',light:'#ffcf89',shadow:'#9c451c',group:'bold'},
{name:'Obsessed',file:'obsessed',photo:'render-3.jpeg',color:'#e48baa',light:'#fbd3df',shadow:'#873452',group:'soft'},
{name:'Night Tale',file:'night-story',photo:'render-2.jpeg',color:'#10284a',light:'#58779c',shadow:'#111b31',group:'afterdark'},
{name:'Soft Chaos',file:'soft-chaos',photo:'render-4.jpeg',color:'#d8c7a9',light:'#f4e9d7',shadow:'#8e7865',group:'soft'},
{name:'Midnight Mood',file:'midnight-mood',photo:'render-3.jpeg',color:'#a61c23',light:'#e7523b',shadow:'#321721',group:'afterdark'},
{name:'Gold Rush',file:'gold-rush',photo:'render-6.jpeg',color:'#e49a16',light:'#ffd76d',shadow:'#926026',group:'bold'},
{name:'Dark Desire',file:'dark-desire',photo:'render-4.jpeg',color:'#12382a',light:'#38724d',shadow:'#0b211d',group:'afterdark'},
{name:'Daydreamer',file:'daydreamer',photo:'render-5.jpeg',color:'#73b8e4',light:'#c1e4f4',shadow:'#347ba1',group:'soft'},
{name:'Delulu',file:'delulu',photo:'render-3.jpeg',color:'#aa80c1',light:'#e4bee7',shadow:'#714882',group:'soft'},
{name:'2 AM',file:'2am',photo:'render-1.jpeg',color:'#25252b',light:'#57545b',shadow:'#111116',group:'afterdark'}
];
const grid=document.querySelector('#product-grid');let cart=[];let toastTimer;
function render(list=products){grid.innerHTML=list.map((p,i)=>`<article class="product-card" style="animation-delay:${i*.035}s"><div class="product-visual photo-${p.photo.split('.')[0]}" style="background:radial-gradient(ellipse at 50% 45%,${p.light} 0%,${p.color}36 48%,${p.color}17 100%);--bottle-color:${p.color};--bottle-light:${p.light};--bottle-shadow:${p.shadow}"><div class="photo-stage"><img class="product-photo" src="assets/${p.photo}" alt="Vela Veli Vo ${p.name} perfume"><div class="native-label-mask"></div><img class="perfume-label" src="assets/${p.file}.png" alt="${p.name} fragrance label"></div><button class="quick-add" data-id="${p.file}">ADD TO BAG&nbsp; +</button></div><div class="product-info"><span class="product-name">${p.name}</span><span class="product-price">DISCOVER ↗</span><span class="product-notes">EAU DE PARFUM</span></div></article>`).join('')}
function updateCart(){document.querySelectorAll('.bag-count').forEach(x=>x.textContent=cart.length);const items=document.querySelector('.cart-items'),content=document.querySelector('.cart-content');if(!cart.length){items.innerHTML='';content.hidden=false;return}content.hidden=true;items.innerHTML=cart.map((p,i)=>`<div class="cart-item"><img src="assets/${p.file}.png" alt=""><div class="cart-item-copy"><strong>${p.name}</strong><span>EAU DE PARFUM</span></div><button class="remove-item" data-index="${i}">Remove</button></div>`).join('')}
grid.addEventListener('click',e=>{const b=e.target.closest('.quick-add');if(!b)return;const p=products.find(x=>x.file===b.dataset.id);cart.push(p);updateCart();const t=document.querySelector('.toast');t.textContent=`${p.name} added to your bag ✳`;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),2100)});
document.querySelector('.cart-items').addEventListener('click',e=>{const b=e.target.closest('.remove-item');if(!b)return;cart.splice(Number(b.dataset.index),1);updateCart()});
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');b.classList.add('active');render(b.dataset.filter==='all'?products:products.filter(p=>p.group===b.dataset.filter))}));
const overlay=document.querySelector('#overlay'),drawer=document.querySelector('.cart-drawer');function openBag(){overlay.classList.add('open');drawer.classList.add('open');document.body.style.overflow='hidden'}function closeBag(){overlay.classList.remove('open');drawer.classList.remove('open');document.body.style.overflow=''}document.querySelector('.bag-btn').addEventListener('click',openBag);document.querySelector('.close-drawer').addEventListener('click',closeBag);overlay.addEventListener('click',closeBag);document.querySelector('.continue').addEventListener('click',closeBag);document.addEventListener('keydown',e=>{if(e.key==='Escape')closeBag()});
document.querySelector('.signup').addEventListener('submit',e=>{e.preventDefault();document.querySelector('.signup-message').textContent='You’re on the list. Talk soon ✳';e.currentTarget.reset()});document.querySelector('.search-open').addEventListener('click',()=>{const row=document.querySelector('.search-row');row.hidden=false;document.querySelector('#collection').scrollIntoView({behavior:'smooth'});document.querySelector('#scent-search').focus()});document.querySelector('#scent-search').addEventListener('input',e=>{const q=e.target.value.trim().toLowerCase();render(products.filter(p=>(p.name+' '+p.group).toLowerCase().includes(q)))});document.querySelector('.search-clear').addEventListener('click',()=>{document.querySelector('#scent-search').value='';render();document.querySelector('#scent-search').focus()});document.querySelector('.mobile-menu').addEventListener('click',()=>{document.querySelector('#collection').scrollIntoView({behavior:'smooth'});document.querySelector('.filter').focus()});render();




